version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: cgapp-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    container_name: painting-ecommerce
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - DB_SSL_MODE=disable
      - SAMPLE_DATA_PATH=/root/platform/migration/sample_data.sql
    networks:
      - my_network

networks:
  my_network:
