name: Deploy to EC2

on:
  push:
    branches:
      - development  # Trigger on pushes to the development branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
          if [ ! -d "deploy/backendservice" ]; then
            mkdir -p deploy
            cd deploy
            git clone -b development https://github.com/Niladri2003/Painting-Ecommerce backendservice
          else
            cd deploy/backendservice
            git pull origin development
          fi
          cd deploy/backendservice
          docker-compose up -d --build
          echo "Deployment complete."
        EOF
