name: Deploy to EC2

on:
  push:
    branches:
      - development  # Trigger on pushes to the development branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
          mkdir -p deploy/backendservice
          cd deploy/backendservice
          if [ -d ".git" ]; then
            git pull origin development
          else
            git clone -b development https://$ACCESS_TOKEN:x-oauth-basic@github.com/Niladri2003/Painting-Ecommerce .
          fi
          docker-compose up -d --build
          echo "Deployment complete."
        EOF
